/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    CesiumPreview: typeof import('./src/components/map/CesiumPreview.vue')['default']
    CodePanel: typeof import('./src/components/layout/CodePanel.vue')['default']
    ExamplePanel: typeof import('./src/components/examples/ExamplePanel.vue')['default']
    GlobalWatermark: typeof import('./src/components/watermark/GlobalWatermark.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NTree: typeof import('naive-ui')['NTree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
  const AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
  const CesiumPreview: typeof import('./src/components/map/CesiumPreview.vue')['default']
  const CodePanel: typeof import('./src/components/layout/CodePanel.vue')['default']
  const ExamplePanel: typeof import('./src/components/examples/ExamplePanel.vue')['default']
  const GlobalWatermark: typeof import('./src/components/watermark/GlobalWatermark.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NTree: typeof import('naive-ui')['NTree']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}